// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type PipelineParkedRun struct {
	RunID             string    `json:"run_id"`
	PipelineName      string    `json:"pipeline_name"`
	NextStageIndex    int32     `json:"next_stage_index"`
	InputForNextStage []byte    `json:"input_for_next_stage"`
	ResumeAt          time.Time `json:"resume_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type PipelineRun struct {
	RunID     string      `json:"run_id"`
	Name      string      `json:"name"`
	Payload   []byte      `json:"payload"`
	Status    string      `json:"status"`
	Result    []byte      `json:"result"`
	Error     pgtype.Text `json:"error"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type PipelineRunStage struct {
	PipelineRunID string      `json:"pipeline_run_id"`
	StageIndex    int32       `json:"stage_index"`
	InputJson     []byte      `json:"input_json"`
	OutputJson    []byte      `json:"output_json"`
	Status        string      `json:"status"`
	Error         pgtype.Text `json:"error"`
	DurationMs    pgtype.Int8 `json:"duration_ms"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}
